In [2]:
import numpy as np

In [3]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.full((5,2),17)

array([[17, 17],
       [17, 17],
       [17, 17],
       [17, 17],
       [17, 17]])

In [6]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(M)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
# assignment!
# 1)create 3 matrices: 2x2, 2x2, 3x2
M1 = np.array([[4,7],[6,8]])
M2 = np.array([[9,3],[2,0]])
M3 = np.array([[8,1,7],[5,2,8]])
# 2)compute scalar-matrix multiplication
print(np.multiply(M1, 3))
print(np.multiply(M2, 7))
print(np.multiply(M3, 6))
# 3) add all pairs of matrices

[[12 21]
 [18 24]]
[[63 21]
 [14  0]]
[[48  6 42]
 [30 12 48]]
